### ISSUE TITLE
Can't start hashbrown on windows

### ISSUE THREAD

**Issue by mirkea-work** [Putaitu/putaitu-cms#194]
Hi.
I can't get hashbrown started on WIndows.
I installed node.js 8 and mongoDB (community server 3.4)
I followed the steps in the guide
```
git clone https://github.com/Putaitu/hashbrown-cms.git -b stable --single-branch
cd ./hashbrown-cms
npm install
node hashbrown.js
```
but I get the following error(s)

https://dl.dropboxusercontent.com/s/pxl9o3wi8fp1w5h/shot_170926_190906.jpg

Any ideas what is the issue?

**Comment by mrzapp** [comment]
Sorry for not seeing this message. It looks like the MongoDB service is not running. Did you activate the service? Try running `mongod` and see the output.

Btw, for future questions, head over to [the subreddit](https://www.reddit.com/r/HashBrownCMS/), this issue tracker is not being monitored for questions :)
