### ISSUE TITLE
Ignore non-hashbrown Mongo databases

### ISSUE THREAD

**Issue by ajmas** [Putaitu/putaitu-cms#200]
When I fired up Hashbrown for the first time I was presented with all my MongoDB databases, even though none of them were Hashbrown related. Wondering whether Hashbrown should be filtering the displayed databases to only include those created by Hashbrown? Maybe based on presence of settings collection and contained value?

**Comment by mrzapp** [comment]
Absolutely, this was originally the intended behaviour. Will fix this.
