### ISSUE TITLE
ctrl-click on MacOS does not bring up contextual menu

### ISSUE THREAD

**Issue by ajmas** [Putaitu/putaitu-cms#202]
The ctrl-click combination on the Mac should be an alternative trigger to bring up the contextual menu, but it does not trigger.

Note: tested with MacOS X 10.13 and Chrome 62.0.x, using MacBook Air, on demo site.

**Comment by mrzapp** [comment]
It uses the 'contextmenu' event, which apparently Mac doesn't simulate properly with CTRL+click. I'll implement it explicitly as an alternative then.

**Comment by mrzapp** [comment]
It uses the 'contextmenu' event, which apparently Mac doesn't trigger properly. I'll implement it explicitly as an alternative, then.

**Comment by mrzapp** [comment]
Implemented in master branch
