### ISSUE TITLE
Getting 404 on the API

### ISSUE THREAD

**Issue by mortenmoulder** [Putaitu/putaitu-cms#212]
I've successfully set up Hashbrown CMS on my server and it works, kinda. I can open the website at http://website.com:8080/ and log in. Here's the issue:

When I go and create a new `Connection`, it successfully does that. I followed [https://github.com/Putaitu/hashbrown-node-driver/tree/example](this example). But when I then go to `Templates`, it is empty. When I then go to create a new Template, it will say:

>http://website.com:8080/api/PROJECT/live/templates/page/test 404 (Not Found)
>Uncaught Error: Couldn't fetch model data
at XMLHttpRequest.request.onload (crisp-ui.js:941)

And then the page refreshes and nothing happens.

If I visit the `http://website.com:8080/api/PROJECT/live/templates/page/test` page (that says 404), it will say:

> Not Found (404) at website.com:8080//hashbrown/api/templates/page/test?token=3340e90b6135a7e2bec659061778ab7b1ddba9f0
> Cannot GET /hashbrown/api/templates/page/test

What could be the issue here? We have tried on 4 different systems now. 2x Windows 10, 1x MacOS, and a Debian server.

**Comment by mrzapp** [comment]
We are currently restructuring the drivers to fit the upcoming HashBrown v1.0 major release, so you may experience some issues there. The release will be ready in 2 days, so you can either wait for that or check out [this commit](https://github.com/Putaitu/hashbrown-node-driver/commit/e75bde338f6b89d529788c2f6b14da83faf3afbf) of the driver.

Sorry for the inconvenience. It's the first major release, so there are a few breaking changes, which should readjust itself automatically once you get the new version.

**Comment by mortenmoulder** [comment]
@mrzapp Oh okay! Awesome. We are doing a CMS project at school, where we had to pick a CMS that we could do a report on, so we decided to go with Hashbrown CMS. We'll wait the two days (or check out the commit) - Thanks!

**Comment by mrzapp** [comment]
Awesome! Let me know if you have any other questions, need a short interview or anything like that. You can hit me up at jeppe@putaitu.com

**Comment by mrzapp** [comment]
The v1.0 of HashBrown is out now! The issues you were having should be resolved now :)

**Comment by mortenmoulder** [comment]
Sounds good, @mrzapp - We'll check it out on Wednesday 👍
