### ISSUE TITLE
Rest API Docs

### ISSUE THREAD

**Issue by kymc** [Putaitu/putaitu-cms#213]
Hello, I was just wondering where I can find the REST API docs?

**Comment by mrzapp** [comment]
Right here: http://hashbrown.rocks/docs/api

They're not 100% complete yet, but the essentials should definitely be there

**Comment by kymc** [comment]
@mrzapp fantastic, thanks 👍

**Comment by mrzapp** [comment]
BTW, please ignore the "http://hashbrown.rocks/docs/api" part of the endpoint URLs, that's a bug I'm fixing now
