### ISSUE TITLE
404 "Markup was empty" when creating new template

### ISSUE THREAD

**Issue by mortenmoulder** [Putaitu/putaitu-cms#215]
We've successfully made our example project by following [the example from the driver](https://github.com/Putaitu/hashbrown-node-driver/tree/example). We got the section and sectionPage to work, and we can view our page online. The section and sectionPage was created initially when we git cloned the project, so we didn't make those. They simply appeared when connecting to our API.

When creating a new template, it simply gives me a:

>Error: Not Found (404) at POST http://localhost:8000/api/templates/page/homePage.html
>Markup was empty at POST http://localhost:8000/api/templates/page/homePage.html

Not sure what's going on. The Node driver is running and everything seems to work except for creating templates.

**Comment by mrzapp** [comment]
Looking into it. In the meantime, just create your templates in the website project in the respective folders. In the case of the example node.js project, it would be /views/(partials/pages)

**Comment by mortenmoulder** [comment]
@mrzapp That's what I've tried. I have this:

<img src="https://i.imgur.com/CgQ8sdq.png" />

and then I have the following files:

<img src="https://i.imgur.com/3NDPOYV.png" />

Then I have the content I've created, which has the "Template" as a Template Reference (according to the schema):

<img src="https://i.imgur.com/KLnQ0xi.png" />

If I save and publish, it will redirect to undefined: `http://mysite.com:8000/undefined` with the error:

>Not Found (404) at GET http://localhost:8000/api/templates/page/myTemplate.html Template by name "myTemplate.html" not found

Not really sure if it's a database issue, since it doesn't know that the file `test.html` actually exists.

**Comment by mrzapp** [comment]
You need to give your page a title, otherwise it has no URL. A patch was submitted to the driver to fix the empty markup issue.

**Comment by mortenmoulder** [comment]
@mrzapp Ah, the more you know. I'll give it a shot soon. Thanks! 😀

**Comment by mrzapp** [comment]
I'll make sure to inform the user when there is no URL too, it would be nicer that way :)

**Comment by mortenmoulder** [comment]
It sure would :-) Thanks a lot for the quick support!
