### ISSUE TITLE
502 gateway error when trying to GET users

### ISSUE THREAD

**Issue by mortenmoulder** [Putaitu/putaitu-cms#216]
As I don't run Hashbrown in a production MongoDB database, but rather in my database with all my other projects (that has nothing to do with Hashbrown), Hashbrown still tries to connect to those databases.

I have a database for my project in Hashbrown (20 random characters) and I have one called `pageviews`. My `pageviews` database has nothing in it but the amount of page views all my websites have (fetched from Google Analytics). It has nothing to do with Hashbrown, but when I go to the `/dashboard/users` page and select one of the users, it will give me this error in the console:

>GET http://my-site.com:8080/api/server/projects 502 (Bad Gateway)
>dashboard.js:30613 Unhandled rejection Error: Project "pageviews" could not be found

I use the new database authentication method you implemented, which is most likely why it's not working (as it doesn't have rights to read the database with the authentication parameters I gave Hashbrown).

**Comment by mrzapp** [comment]
I see. We probably need a prefix for all HashBrown databases, then.

**Comment by mrzapp** [comment]
This has now been fixed in the stable branch. You can now add a "prefix" to the database config. Check out the [documentation](http://hashbrown.rocks/guides/configuring-the-database/) on the feature for help with renaming your existing databases
