### ISSUE TITLE
error after fresh install

### ISSUE THREAD

**Issue by traskat** [Putaitu/putaitu-cms#218]
hey,

i get  error after i followed the getting started guide.
it cannot connect to the mongo db:
```
/home/user/sources/hashbrown-cms/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

Error: MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at MongoClient.connect (/home/user/sources/hashbrown-cms/src/Server/Helpers/DatabaseHelper.js:236:28)
    at connectCallback (/home/user/sources/hashbrown-cms/node_modules/mongodb/lib/mongo_client.js:507:5)
    at /home/user/sources/hashbrown-cms/node_modules/mongodb/lib/mongo_client.js:414:11
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
then i created the config directory and in that a database.cfg which contains only that:
```
{
   "url":"172.17.0.3"
}
```
then hashbrown can connect to the mongodb, but then it says database config already exists.
node version : 8.11.1

**Comment by mrzapp** [comment]
This is a problem with the init setup flow, you can't use a database on another server just yet. You can get around it by either using MongoDB on localhost (same server as HashBrown app) or by using the commandline to create your first admin account instead of using the UI.

```
node hashbrown.js create-user u=<USERNAME> p=<PASSWORD> admin=true
```

**Comment by traskat** [comment]
@mrzapp i created a admin user as you said, but i still get the same error. Also i always get redirect to the setup url where this error occurs.
Anything else i can do execpt of the installation of on my local machine? i would like to use a docker container for that.

thanks

**Comment by mrzapp** [comment]
@traskat I created a new release (v1.0.6) with a docker-compose file. The database config error is fixed too.

**Comment by mrzapp** [comment]
@traskat It's worth noting that this breaks the backup system, as the node container cannot directly invoke the "mongodump" and "mongorestore" commands. Those are only executable from within the mongodb container. You can always just have your own backups using the Docker volume, of course.

I will have to find a solution for that.

**Comment by traskat** [comment]
@mrzapp couldn't you just take a nodejs module for that? something like that
https://github.com/hex7c0/mongodb-backup

**Comment by mrzapp** [comment]
@traskat that's interesting, I'll dive into that module
