### ISSUE TITLE
Adjust UI to be tablet friendly: alternatives to context clicking

### ISSUE THREAD

**Issue by ajmas** [Putaitu/putaitu-cms#220]
I opened the demo on my iPad and there was no apparent way to do anything, other than navigate around. It is only once you get on the desktop that you see that right-clicking brings up a context menu.

While I am not sure how support for tablets fits into the target market, it would be useful to adjust the user interface to work without needing right-clicking. My own experience has been that users don't expect to right-click in a web page for non-browser specific functionality. I must admit that even on the desktop it wasn't obvious how to reach the functionality. 

I am not a UI expert myself, but possible suggestions:
  - menubar or toolbar across top of sub-section
  - widget on items that can be tapper or left-clicked on to bring up menu

**Comment by mrzapp** [comment]
You can long press to open the context menu. That doesn't work for you?

**Comment by ajmas** [comment]
I wouldn’t have thought of that, since it is not the type of user interaction most people are used to.

I just tried and it does not work. Instead, I just get the browser option to magnify or select.

**Comment by mrzapp** [comment]
Ok, it seems Safari is having some trouble with it. I think I'll add the widget you're talking about, it could be an elegant solution.

**Comment by mrzapp** [comment]
@ajmas sorry for the long wait, this ticket is resolved in v1.2
