### ISSUE TITLE
Connections, templates and more

### ISSUE THREAD

**Issue by internetstyle** [Putaitu/putaitu-cms#221]
Hello. I'm taking a look at the CMS and found the idea very interesting.

However, I'm not very understanding the part of connections and templates.

In the templates part, how do I make a dynamic template with data coming from a schema?

I want a Headless CMS to integrate with Gatsbyjs, and if I understand better I can create this integration. Thanks.

**Comment by mrzapp** [comment]
Hello. This isn't much of an issue, rather a question, which we prefer to answer on our subreddit: https://www.reddit.com/r/HashBrownCMS/

But to give you a quick rundown:
- Connections are what HashBrown uses to communicate with your web server
- Your webserver has all of the static content, including templates and media files
- A connection can be set up to read templates from a given directory on your web server
- Your web server has to be either a GIT repo or have an API that can serve the template files back to HashBrown (see the hashbrown-driver) repos
