### ISSUE TITLE
Deploy the site

### ISSUE THREAD

**Issue by seoeaa** [Putaitu/putaitu-cms#223]
so I did not understand how to deploy the site

**Comment by mrzapp** [comment]
All HashBrown does is deploy the content through Git (remote), an API (remote) or its own filesystem (local). Your site on the server (remote or local) then presents the content to the world however you like. The content can be in JSON or Jekyll format as of right now.

If you want to add your own format, like XML for instance, you can take a look at how the "json" plugin does it: https://github.com/HashBrownCMS/hashbrown-cms/tree/master/plugins
