### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by seoeaa** [Putaitu/putaitu-cms#224]
Forbidden (403) at GET https://api.github.com/repos/Putaitu/hashbrown-cms/releases/latest {"message":"API rate limit exceeded for 78.0.0.0. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}

**Comment by mrzapp** [comment]
What kind of network are you on? The IP "78.0.0.0" seems a bit suspicious to me :)
