### ISSUE TITLE
Move documentation to GitHub wiki?

### ISSUE THREAD

**Issue by mrzapp** [Putaitu/putaitu-cms#225]

**Comment by raspher** [comment]
I suggest move API etc. to wiki pages, but leave installation and uncomplicated troubleshoots on gh-pages.

This should separate _dev_ stuff from _production_ releases, as well give clean documentation for end users and for developers.

**Comment by mrzapp** [comment]
@uzerus That's a good point. I'll give this another look once v1.1 is out.

**Comment by mrzapp** [comment]
Taking another approach, as the API docs are automatically generated, they are not a good candidate for the wiki.

Instead, the guides will be moved to the wiki, but also available from the main site via scraping.

**Comment by mrzapp** [comment]
@milesleif @nkear003 @silend This task is now done, the wiki now contains all guides, and the HashBrown website scrapes them.

If we find anything worth documenting, we should add it to the wiki from now on. Let's have a chat about this before launching v1.2
