### ISSUE TITLE
Make media files searchable/sortable by alpha/date

### ISSUE THREAD

**Issue by mrzapp** [Putaitu/putaitu-cms#229]

**Comment by mrzapp** [comment]
@milesleif I've added this functionality to all panels now, Media included (however, date sorting doesn't work there, since change dates are not available in list form for binary files yet).

Does it work the way you were expecting?

**Comment by mrzapp** [comment]
@silend is this issue OK to close?

**Comment by silend** [comment]
@mrzapp Very okay, great solution!
