### ISSUE TITLE
Editor for "Rich Text" should be configurable for Markdown ⁄ plain text. A setting on the FieldSchema

### ISSUE THREAD

**Issue by mrzapp** [Putaitu/putaitu-cms#236]

**Comment by mrzapp** [comment]
@milesleif I've upgraded to WebPack 4 now, so it should work with the latest code from master. 

The file in question is [this one](https://github.com/HashBrownCMS/hashbrown-cms/blob/master/src/Client/Views/Editors/FieldEditors/RichTextEditor.js), and the method is "renderConfigEditor". I've created an example in there for disabling the markdown editor, but it's not implemented in the frontend.

Look around in this file for occurrences of "html", "wysiwyg" and "markdown" to find where you need to use the config.isMarkdownDisabled to prevent the use. Please let me know if you I can do more to help you.

**Comment by silend** [comment]
Related to #251 and postponed for v1.2

**Comment by mrzapp** [comment]
Fix pushed to v1.2 branch
