### ISSUE TITLE
UX: main view should change when toolbar is clicked, or it should be more obvious why it doesn't

### ISSUE THREAD

**Issue by mrzapp** [Putaitu/putaitu-cms#238]

**Comment by mrzapp** [comment]
@milesleif @silend please type your suggestions here that you mentioned during our talk

**Comment by milesleif** [comment]
@mrzapp if I recall correctly, the idea was to work with hover states in that way: 

- Hover over the far left icons changes sidebar next to it accordingly, main view remains untouched
- Click on far left icons clears main view and "locks" sidebar view

This is not suitable for touch displays of course but we thought that using a touch device is a pretty edge case anyway.

@silend @nkear003 am I mistaken or do I forget another approach?
