### ISSUE TITLE
When re-sorting components: If you hit "save" before "done sorting" you end up having all components alphabetical. And sometimes even when you just press "done sorting"

### ISSUE THREAD

**Issue by mrzapp** [Putaitu/putaitu-cms#239]

**Comment by mrzapp** [comment]
@milesleif I can't seem to reproduce this, do you have an example of it? And in which browser did this happen?

**Comment by mrzapp** [comment]
@milesleif I still haven't been able to reproduce, should we close this issue for now, or has it happened again since?

**Comment by milesleif** [comment]
@mrzapp We tried hard, but we couldn't reproduce that bug either. Maybe it had something to do with corrupt data or some very specific chaotic circumstances we cannot recreate. I guess we can close this issue.

**Comment by mrzapp** [comment]
Done ;)
