### ISSUE TITLE
ResourceHelper: Use HTML5 database for caching references to database resources

### ISSUE THREAD

**Issue by mrzapp** [Putaitu/putaitu-cms#243]
Instead of having JSON objects and arrays in RAM, we should use HTML5 database to store just the essentials of the resources.

We will refresh this content periodically, like once a minute and upon saving changes.

**Comment by mrzapp** [comment]
@silend I've refactored the entire resource cache backend to be asynchronous using IndexedDB.

The situation before was that when all content was preloaded, it was stored in the `window.resources` variable, taking up more and more memory in the browser as content was added.

Now, it's stored in the IndexedDB, which is asynchronous and not a memory hog.

This was a lot of work with many changes, so a general UI test will be needed here, although I've been testing extensively myself.

**Comment by silend** [comment]
Works just fine in my tests.
