### ISSUE TITLE
npm install incompatible module error

### ISSUE THREAD

**Issue by guyjacks** [Putaitu/putaitu-cms#244]
node v10.13.0

I cloned the repo as instructed and then ran yarn inside the cloned project.  The install failed with the following errors.

```
$ yarn
yarn install v1.12.3
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning production > cheerio > cheerio-select > CSSselect@0.7.0: the module is now available as 'css-select'
warning production > cheerio > cheerio-select > CSSselect > CSSwhat@0.4.7: the module is now available as 'css-what'
warning to-markdown@2.1.0: to-markdown has been renamed to Turndown, with a new API. Please update to turndown v4.0.0 or above and see the migration guide for details: https://github.com/domchristie/turndown/wiki/Migrating-from-to-markdown-to-Turndown
warning babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
warning babel-preset-es2015-native-modules > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[2/4] 🚚  Fetching packages...
error to-markdown@2.1.0: The engine "node" is incompatible with this module. Expected version "^4". Got "10.13.0"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by mrzapp** [comment]
Ok, haven't tried this with yarn before. It looks like the module "to-markdown" could use an upgrade. Could you try using the latest version and running it again?

In any case, unless you are developing on the frontend, you should use the "production" flag, like so: yarn install --production.

If all else fails, run npm install --production

**Comment by guyjacks** [comment]
npm install --production ...worked.
yarn install --production ...did not work.

That said, there appear to be security vulnerabilities (would you like me to create a ticket with the audit?).

    found 4 vulnerabilities (3 moderate, 1 high)
    run `npm audit fix` to fix them, or `npm audit` for details

Also, node hashbrown.js does not seem to work (should I create a ticket?).

```
$ node hashbrown.js
/Users/guyjacks/projects/practice/headless_cms/hashbrown-cms/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

Error: MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at MongoClient.connect (/Users/guyjacks/projects/practice/headless_cms/hashbrown-cms/src/Server/Helpers/DatabaseHelper.js:245:28)
    at connectCallback (/Users/guyjacks/projects/practice/headless_cms/hashbrown-cms/node_modules/mongodb/lib/mongo_client.js:527:5)
    at /Users/guyjacks/projects/practice/headless_cms/hashbrown-cms/node_modules/mongodb/lib/mongo_client.js:418:11
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

These instructions do not mention configuring MongoDB: http://hashbrown.rocks/getting-started/

**Comment by mrzapp** [comment]
MongoDB is rather casually mentioned as a requirement, I never thought of providing setup instructions for it. You can always set it up via Docker, if you're familiar with that, there is a docker-compose.yml in the root folder. I recommend using the one from the master branch, as it has a few unreleased improvements.

It'd be great with a ticket including the audit, or even better, a pull request fixing the issue in the package.json if you have the time. If you get yarn working, a pull request for that would be highly appreciated too :)

I will have time to look into this about a week from now, should you not end up resolving it.

**Comment by silend** [comment]
`yarn` and `yarn install --production` now both work using

+ Yarn v1.12.3
+ Node.js v8.12.0 & v10.13.0

This has been probably fixed through 1dd09542.

**Comment by mrzapp** [comment]
That's great, the dependencies were definitely due for an update.

**Comment by silend** [comment]
Related to #252
