### ISSUE TITLE
Demo broken on Chrome

### ISSUE THREAD

**Issue by lukas-schaetzle** [Putaitu/putaitu-cms#245]
The provided demo on the homepage has problems with the newest Chromes version and does often not show the right content on the right side when selecting  an entry from the menu (e.g. when clicking on Content > HashBrown CMS, the right side just stay empty whereas it works with Firefox.) Same problem for menu entries under the schema tab.

**Comment by mrzapp** [comment]
@Tummerhore is this still the case? I've been testing with the latest Chrome now, and I can't reproduce the problem. Are there errors in the console?

**Comment by lukas-schaetzle** [comment]
For me it's still broken (latest Chrome version 71.0.3578.98 (64 bit)). Right side just stays empty like in this screenshot:
![unbenannt](https://user-images.githubusercontent.com/45203603/50516914-c9a27d00-0aad-11e9-812f-76c74963951a.png)

Error in console when clicking the shown entry:
Uncaught TypeError: Parameter "childSchema" is of type "Object", should be "Schema". Value was: {"id":"page","name":"Page","icon":"file","parentSchemaId":"contentBase","isLocked":true,"sync":{},"hiddenProperties":[],"defaultTabId":"content","tabs":{"content":"Content"},"fields":{"properties":{"title":{"label":"Title","schemaId":"string","tabId":"content"},"description":{"label":"Description","schemaId":"string","tabId":"content"},"url":{"label":"URL","schemaId":"url","tabId":"content"},"template":{"label":"Template","schemaId":"templateReference","tabId":"content","config":{"allowedTemplates":[]}}}},"allowedChildSchemas":[],"type":"content"}
    at base.checkParam (client.js:29589)
    at Function.mergeSchemas (client.js:26111)
    at demo.js:635

**Comment by mrzapp** [comment]
@Tummerhore  I've updated the demo.js file now, can you check again?

**Comment by lukas-schaetzle** [comment]
Ok, it works now. Thanks for fixing it.

**Comment by mrzapp** [comment]
Thanks for reporting it :)
