### ISSUE TITLE
Case sensitivity is hindering webpack to work properly on OSX

### ISSUE THREAD

**Issue by milesleif** [Putaitu/putaitu-cms#247]
On a non-case-sensitive system (like OSX is by default) particularly `src/Client/client.js` and `src/Client/dashboard.js` are having issues do decide which file to include when calling both

```
require('Client/helpers');
```
and
```
require('Client/Helpers');
```

First notation should look for the helpers.js, second notation for index.js inside /Helpers.

Warning reads

```
WARNING in ./src/Client/Helpers.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /Users/miles/webs/hashbrown-test/hashbrown-cms/node_modules/babel-loader/lib/index.js??ref--0!/Users/miles/webs/hashbrown-test/hashbrown-cms/src/Client/Helpers.js
    Used by 2 module(s), i. e.
    /Users/miles/webs/hashbrown-test/hashbrown-cms/node_modules/babel-loader/lib/index.js??ref--0!/Users/miles/webs/hashbrown-test/hashbrown-cms/src/Client/dashboard.js
* /Users/miles/webs/hashbrown-test/hashbrown-cms/node_modules/babel-loader/lib/index.js??ref--0!/Users/miles/webs/hashbrown-test/hashbrown-cms/src/Client/helpers.js
    Used by 2 module(s), i. e.
    /Users/miles/webs/hashbrown-test/hashbrown-cms/node_modules/babel-loader/lib/index.js??ref--0!/Users/miles/webs/hashbrown-test/hashbrown-cms/src/Client/dashboard.js
 @ ./src/Client/Helpers.js
 @ ./src/Client/dashboard.js
```

and is creating broken js-files inside the public folder.

**Comment by milesleif** [comment]
@mrzapp maybe you have quick Idea how to solve this? I tried https://github.com/Urthen/case-sensitive-paths-webpack-plugin (unsuccessful so far) but since this might be the only occurrence of a case issue (and avoided by some adjustments in the naming convention), I'd rather not use a sledgehammer to crack a nut.

**Comment by mrzapp** [comment]
@milesleif I suggest renaming helpers.js to utilities.js for now
