### ISSUE TITLE
Add a "label" dropdown to the Struct config editor

### ISSUE THREAD

**Issue by mrzapp** [Putaitu/putaitu-cms#250]

**Comment by nkear003** [comment]
![bildschirmfoto 2019-01-17 um 17 55 33](https://user-images.githubusercontent.com/24900791/51335197-ba499a80-1a81-11e9-9818-925be0bd892c.png)

@mrzapp Hey Jeppe, when you don't change the field name from the default (newField), no name appears when you collapse the entire field (picture above). 

When you change the name of the field to even newField1 (New field 1), the name of the field appears in the collapsed array. I don't think anyone will use the default names, but just a heads up :) Going to move this to done.

![image](https://user-images.githubusercontent.com/24900791/51335697-021cf180-1a83-11e9-8a21-22adeeec8b81.png)

**Comment by mrzapp** [comment]
@nkear003 Ok, I'll reference this issue later then, since the bug is so minor
