### ISSUE TITLE
CKEditor bugs out sometimes

### ISSUE THREAD

**Issue by mrzapp** [Putaitu/putaitu-cms#251]
CKEditor will sometimes, possibly because of async issues, not load properly.

TypeError: a.ui.space(...) is null

Should we drop this buggy mess entirely, or is there a good fix around?

**Comment by silend** [comment]
If you think about replacing CKEditor altogether, this is my personal short-list:

+ [Quill](https://quilljs.com/)
+ [Trix](https://trix-editor.org/)
+ [ProseMirror](https://prosemirror.net/)

**Comment by mrzapp** [comment]
Nice! ProseMirror looks neat and simple. With simplicity in mind, and considering the implementation needs, which one do you think is the best fit?

We just need to be able to strip unwelcome styling tags and refactor the media URLs when updating the content as you might be able to tell from [these lines](https://github.com/HashBrownCMS/hashbrown-cms/blob/master/src/Client/Views/Editors/FieldEditors/RichTextEditor.js#L209-L306)

**Comment by silend** [comment]
I agree that ProseMirror seems to be a good fit for HashBrown.

Stripping and refactoring should be do-able with `inputrules` and `transform`.

**Comment by silend** [comment]
@mrzapp **Editor.js** is also worth mentioning: https://editorjs.io/ … the clean JSON looks very good.

**Comment by mrzapp** [comment]
@silend ooh I like that one. I'll have a look at the options concerning markdown and code editing

**Comment by mrzapp** [comment]
@silend After a lot of testing and research, I've come to the conclusion that the amount of work needed to properly integrate any third-party editor outweighs the amount of work needed for building one from scratch.

So that's what I did. It's around 200 lines of code using standard JavaScript APIs that have become standard since these other editors were invented.

The code is ready for testing in the [v1.2](https://github.com/HashBrownCMS/hashbrown-cms/tree/v1.2) branch.

![WYSIWYG](https://i.imgur.com/72ZX4QZ.png)
