### ISSUE TITLE
hashbrown test template and language

### ISSUE THREAD

**Issue by fturiot** [Putaitu/putaitu-cms#261]
Hi,
i don't understand how we can add and manage template , i have no template provider found

Interface not in french can you send me information for add french language

thanks

**Comment by mrzapp** [comment]
Hello,

Templates are being deprecated very soon, since they provided very little value and were demanding to maintain.

Currently, there is no way to change the UI language.

Also, support questions are best asked in the subreddit: reddit.com/r/HashBrownCMS
