### ISSUE TITLE
User List UI messed up

### ISSUE THREAD

**Issue by AndreLion** [Putaitu/putaitu-cms#262]
reproduce version : master branch (01157567dbcc21509eb38a8261ef03e31a289069)
<img width="954" alt="screen shot 2019-02-19 at 14 48 40" src="https://user-images.githubusercontent.com/85134/52995533-e5932100-3455-11e9-9d8d-9b222b3908d1.png">

The user item should be a bar instead of a card, otherwise we have re-deigned this page since 1.9.0

**Comment by mrzapp** [comment]
That is not intentional 😅 Which browser are you seeing this in? And are you on the master or the stable branch?

Actually, the user directory might look better as a grid, looking at it this way, @milesleif what do you think?

**Comment by milesleif** [comment]
@mrzapp true, actually not a bad idea to display users in the same grid manner as the projects. This would also provide room for more meta info for each user at first glance.

(but still @AndreLion, the behavior seen in the screenshot is not expected; more info is needed)

**Comment by silend** [comment]
@milesleif @mrzapp I can reproduce what @AndreLion is seeing on the current `master` branch, both in Chrome and Firefox:

![bildschirmfoto 2019-02-19 um 12 49 20](https://user-images.githubusercontent.com/2743576/53013074-20408d80-3445-11e9-8932-38e52c7bd6c4.png)
![bildschirmfoto 2019-02-19 um 12 50 03](https://user-images.githubusercontent.com/2743576/53013075-20408d80-3445-11e9-8b5b-5e2ea86f4adb.png)

**Comment by AndreLion** [comment]
Added version number for reproduction: master branch (01157567dbcc21509eb38a8261ef03e31a289069) in all major browsers.

**Comment by mrzapp** [comment]
@milesleif if you've got some ideas for how to represent these, feel free to style them as you see fit.

**Comment by mrzapp** [comment]
@milesleif I have taken this task upon me, as the markup is admittedly a little slapdash for this particular element. I'll create a task to clean that up, but for now, this is the solution I've applied:

![image](https://user-images.githubusercontent.com/2747428/53417729-7c238d00-39d6-11e9-8ccc-fd5ce7c4977d.png)
![image](https://user-images.githubusercontent.com/2747428/53417754-86de2200-39d6-11e9-9f23-dca6d6a3b08b.png)
![image](https://user-images.githubusercontent.com/2747428/53417765-91002080-39d6-11e9-9ddb-f9d55adc8695.png)

@silend this is ready for testing, although I'm 99% sure it works as intended.

**Comment by silend** [comment]
@mrzapp With the latest updates on `master` the user section remains blank and I am seeing the following error in console:

<img width="523" alt="bildschirmfoto 2019-02-26 um 15 09 54" src="https://user-images.githubusercontent.com/2743576/53418785-dde4f680-39d8-11e9-9dcf-b82a493979c8.png">

What am I missing?

**Comment by mrzapp** [comment]
@silend yeah, you don't have the Git submodules. You need to run `git submodule update --init` to fetch them. Next time, when you're cloning fresh, you can append `--recursive` to the `git clone` command.

**Comment by mrzapp** [comment]
Maybe we should implement a check for that, I'll get on it.

**Comment by silend** [comment]
@mrzapp Of course, my bad. Such a check would be neat, but maybe not urgent, it’s quite clear in the README, just skipped that part 🙈  It works now, thank you.

**Comment by silend** [comment]
@mrzapp I can confirm it to work in major browsers, and it looks good!
I’d suggest sorting the entries by the title though and not by creation date, as it will be even harder with the new card style if there are a lot of users:

![hb-userlist](https://user-images.githubusercontent.com/2743576/53423946-94010e00-39e2-11e9-9edb-6b508623b38b.png)

![bildschirmfoto 2019-02-26 um 16 12 44](https://user-images.githubusercontent.com/2743576/53423976-9c594900-39e2-11e9-8c4d-0cb7ab177db7.png)

**Comment by mrzapp** [comment]
@silend that should work now

**Comment by silend** [comment]
@mrzapp Yes, much better. Thanks!
