### ISSUE TITLE
Automatic update v1.0 —› v1.1 is failing

### ISSUE THREAD

**Issue by silend** [Putaitu/putaitu-cms#268]
The automatic upgrade using `git` seems to fail.

Users see this modal dialogue when attempting to upgrade:
![bildschirmfoto 2019-03-05 um 10 42 07](https://user-images.githubusercontent.com/2743576/53808388-5b1ce800-3f52-11e9-8ccc-71ed9c7abfcc.png)

Console error output:
```
App 1409 output: 2019.03.05 09:41:26 | UpdateHelper | Updating HashBrown...
App 1409 output: 2019.03.05 09:41:27 | UpdateHelper | Checking out stable branch...
App 1409 output: 2019.03.05 09:41:27 | ServerController | ERROR: Error: Failed to check out the "stable" branch with GIT
App 1409 output:     at ChildProcess.git.on (/var/www/hashbrown/code/src/Server/Helpers/UpdateHelper.js:106:32)
App 1409 output:     at emitTwo (events.js:126:13)
App 1409 output:     at ChildProcess.emit (events.js:214:7)
App 1409 output:     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```
It might be a good idea to give users more insight or provide them with the necessary steps to manually resolve the issue.

**Comment by mrzapp** [comment]
@silend the next update to v1.2 will probably fail too, as we're removing the /plugins directory from the main repo. How do you suppose we can improve the experience? For now, I'll just add a line explaining how to resolve it manually.
