### ISSUE TITLE
After Update to 1.1: Struct within Struct throws Uncaught TypeError: Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by milesleif** [Putaitu/putaitu-cms#270]
This is a quite urgent problem since it breaks nearly all of our currently set up projects. 

**Abstract**
Schemas using StructEditors inside other StructEditors as part of an Array inside Content Base Schemas are causing problems (I know, that's Levellevellayer-Inception-talk, but bear with me).

**Reproduction**

Using Hashbrown latest stable (v 1.1).

Set up the following schemas (names don't matter, I just use them in this way for better understanding): 

***Simple Component*** (as child of "Struct" Field Base)
use the following config: 

```
    "config": {
        "struct": {
            "my_field": {
                "label": "My field",
                "schemaId": "struct",
                "config": {
                    "struct": {}
                }
            }
        }
    }
```

***Simple Base*** (as child of Content Base)
with the following fields

```
    "fields": {
        "properties": {
            "components": {
                "label": "Components",
                "schemaId": "array",
                "tabId": "meta",
                "config": {
                    "allowedSchemas": [INSERT_SIMPLE_COMPONENT_ID]
                }
            }
        }
    }
```

Create a content (from here on called "Simple Content") with the Simple Base Schema and try to insert a new Component in the respective section.

**What should happen**

Our Simple Component should be added nicely to the array of components and we should be able to edit it's contents (though in this example there is none) as well as adding further components.

**What is happening currently**

We are getting an modal with an error "Uncought TypeError: Cannot read property 'config' of undefined". Component is not added, content did not change.

![config-of-undefined](https://user-images.githubusercontent.com/1314903/53882819-a0571d80-4017-11e9-81d2-c5f528bd502e.gif)

**Other observations**

We have a lot of projects which use that [Array in Content Base] > [Component Struct]  > [Fields within Component also using Structs] architecture and so we encountered this error first when we were trying to access our content after the Update to Hashbrown Version 1.1. We get the same error when the Editor tries to render all Inputs and after confirmation of the modal we are thrown to the json view of the content.

![config-of-undefined-in-real-life](https://user-images.githubusercontent.com/1314903/53882941-004dc400-4018-11e9-9f08-4aa6bfdbf5b4.gif)

At some point I also got a browser console error which might help to follow the trail to the origin of the error.

![bildschirmfoto 2019-03-06 um 12 47 22](https://user-images.githubusercontent.com/1314903/53883226-b1ecf500-4018-11e9-8fc0-7ed04cdb2422.jpg)

**Suspicion**

The only line in the code where we are thrown to the json-view after an error is found in `ContentEditor.js` Line 556. Thus I suspect some part of the then-block of the `HashBrown.Helpers.SchemaHelper.getSchemaWithParentFields`-promise not to work correctly. Inside the same file there are multiple accesses to a `config`-property of `fieldDefinition` which is a part of the `schema` returned by the same promise. 

Could it be that `fieldDefinition` is somehow not defined due to `getSchemaWithParentFields` not returning a usable answer? 

**Other effects**

This issue also applies when Simple Component is not using a StructEditor itself but its parent does. E.g. "Simple Component Parent" would use a StructEditor for defining its input, "Simple Component Child" would not => using "Simple Component Child" as only allowed Schema on "Simple Base" > Components results in the same error when trying to add it.

**Comment by mrzapp** [comment]
@milesleif I'm on it

**Comment by mrzapp** [comment]
@milesleif can you test with the latest master? I've tested against the setup you described and can't reproduce the error anymore.

The error seems to be that the StructEditor was passing a part of the configuration to each field as a schema rather than the FieldSchema it was supposed to consume, but only if the struct was not inherited yet. A rather particular scenario I haven't bumped into before now

**Comment by milesleif** [comment]
@mrzapp thank you very much. The bug seems to be gone, our arraystructstructs are working again. :) 

We noticed you also commited it to the stable branch, I assume a new version/tag (patch level) would be a good idea?

**Comment by mrzapp** [comment]
@milesleif Yep, just about to bump the version number now
