### ISSUE TITLE
API deployer is failing (v1.1)

### ISSUE THREAD

**Issue by silend** [Putaitu/putaitu-cms#271]
Since the update to v1.1 the deployer of type `API` seems to have issues.
We are using this deployer type as publishing connection for our projects.

No matter the URI specified, an error message is shown:

+ Using `docker-compose -d up` locally: ![Bildschirmfoto 2019-03-12 um 13 53 38](https://user-images.githubusercontent.com/2743576/54347219-dcf1cd00-4646-11e9-991d-3346abe8c06e.png)

+ Using our production server: ![Bildschirmfoto 2019-03-12 um 13 53 51](https://user-images.githubusercontent.com/2743576/54347283-fdba2280-4646-11e9-9faa-76e12777761d.png)

The production environment used to work fine before the upgrade.

**Comment by mrzapp** [comment]
@silend does this error come up when you publish content, or somewhere else? Can I see the connection's JSON from the "advanced" view? (any incriminating data censored, of course)

**Comment by mrzapp** [comment]
@silend can you check with the latest master? It seems the Path.join function in the HashBrown.Models.Deployer::getPath method was to blame. It was appending a "/" to the "https"

**Comment by silend** [comment]
@mrzapp Yes, the current version in `master` works just fine 👍

**Comment by mrzapp** [comment]
@silend OK, then I'll create a new release tag with the fix on stable
