### ISSUE TITLE
uischema.org importer and processor

### ISSUE THREAD

**Issue by mrzapp** [Putaitu/putaitu-cms#272]

**Comment by mrzapp** [comment]
@silend I've added preliminary support for an importer, it's on the "Schemas" page now ![image](https://i.imgur.com/4BwvB9E.png)

**Comment by mrzapp** [comment]
@silend The importer and deployer are now ready for testing

**Comment by silend** [comment]
It works as expected, when importing all schemas at once, eg. `https://uischema.org/all.json`.

It does not work when importing a single schema, which has a parent (that has not been previously imported), eg. `https://uischema.org/Hero.json`, which then would miss the @parent `feature`.
No schemas at all will be displayed then, until the missing parent dependency is add, for example by importing `all.json`.

**Comment by mrzapp** [comment]
@silend ah, that makes sense. Should we automatically import the parent then, or should we warn the user that the parent doesn't exist?

**Comment by mrzapp** [comment]
A two-step process involving a confirmation dialogue is preferred

**Comment by mrzapp** [comment]
@silend I've implemented a dependency warning for now, I'm making a 2 step issue for v1.3

**Comment by silend** [comment]
@mrzapp The warning does not display in the UI when importing a schema with a missing dependency. The behaviour remains unchanged and no schema will be displayed afterwards.

![2019-06-10-161623_1849x451_scrot](https://user-images.githubusercontent.com/2743576/59201897-be469800-8b9b-11e9-80d1-6cbb065f743a.png)

**Comment by mrzapp** [comment]
![image](https://user-images.githubusercontent.com/2747428/59203770-8e998f00-8b9f-11e9-9356-6f83b8bbb7d8.png)

@silend You sure you're on the latest v1.2?

**Comment by silend** [comment]
@mrzapp My bad. After stopping and re-starting the docker containers everything looks as expected. Sorry!

**Comment by mrzapp** [comment]
@silend no worries. For a quick restart, you can also `touch package.json`, then HashBrown will restart itself.
