### ISSUE TITLE
DB connection improvment

### ISSUE THREAD

**Issue by AndreLion** [Putaitu/putaitu-cms#275]
- pass `options` from `process.env.MONGODB_OPTIONS`.
- pass `prefix` from `process.env.MONGODB_PREFIX`.
- support multiple `hosts`/`ports` in connection string ([official standard](https://docs.mongodb.com/manual/reference/connection-string/#standard-connection-string-format)). 
- code improvement.

**Comment by mrzapp** [comment]
@AndreLion are you referring to [this](https://github.com/HashBrownCMS/hashbrown-cms/blob/master/src/Server/Helpers/DatabaseHelper.js#L44) ?

**Comment by AndreLion** [comment]
> @AndreLion are you referring to [this](https://github.com/HashBrownCMS/hashbrown-cms/blob/master/src/Server/Helpers/DatabaseHelper.js#L44) ?

yes, will provide PR later.

**Comment by AndreLion** [comment]
Hi @mrzapp , PR #276 is ready for review.
