### ISSUE TITLE
Remove webpack generated files out of git?

### ISSUE THREAD

**Issue by AndreLion** [Putaitu/putaitu-cms#279]
Pros of removing `webpack` generated files out of git are obvious.  (clean code commit & review and less conflicts).

How about we combine `webpack` and `node hashbrown.js` into `npm start` shortcut command, to compile the static files from src every time user start the application?

**Comment by mrzapp** [comment]
@AndreLion I agree, let's do that. Could you also create a `npm dev` command which passes the `--watch` option to webpack?

**Comment by mrzapp** [comment]
@AndreLion on the `v1.2` branch, if you don't mind.

**Comment by mrzapp** [comment]
@AndreLion as I realised that it might be a bit hard to work out which scripts to unversion, I went ahead and did it. I created a few npm scripts in the package.json, please let me know if you have any comments there, like if you would like scripts that don't involve docker for instance.

**Comment by AndreLion** [comment]
Hi @mrzapp , yes, considering non-docker users (like me), I added some npm scripts. Please checkout my proposal in #281

**Comment by mrzapp** [comment]
@AndreLion merged :+1:
