### ISSUE TITLE
connect mongodb with srv protocal, and no port

### ISSUE THREAD

**Issue by ghost** [Putaitu/putaitu-cms#282]
like: mongodb+srv://anker:<password>@xxxx-yyyy.mongodb.net/test?retryWrites=true
so i recommend in DatabaseHelper.js
line: 53
del:            case 'port':
del:                return '27017';
add:            case 'protocal':
add:                return 'mongodb://';
line: 75
del:            let connectionString = 'mongodb://';
add:           let connectionString = this.getConfig('protocal');

**Comment by mrzapp** [comment]
[This commit](https://github.com/HashBrownCMS/hashbrown-cms/commit/d84bba4ebf2f0076547870e78b689560a9a550eb) should fix it.

Now you can either specify it like this in the `/config/database.cfg`:

```
{
    "protocol": "mongodb+srv"
}
```

Or like this as an environment variable:

```
MONGODB_PROTOCOL="mongodb+srv"
```

As for "no port", I don't see how that's possible. If you specify no port, the client will default it to 27017 anyway?

**Comment by ghost** [comment]
> [This commit](https://github.com/HashBrownCMS/hashbrown-cms/commit/d84bba4ebf2f0076547870e78b689560a9a550eb) should fix it.
> 
> Now you can either specify it like this in the `/config/database.cfg`:
> 
> ```
> {
>     "protocol": "mongodb+srv"
> }
> ```
> 
> Or like this as an environment variable:
> 
> ```
> MONGODB_PROTOCOL="mongodb+srv"
> ```
> 
> As for "no port", I don't see how that's possible. If you specify no port, the client will default it to 27017 anyway?

thanks for answer,
about "no port", it because of i used the mongodb.com atlas service,
the sandbox url is just "mongodb+srv://anker:@xxxx-yyyy.mongodb.net/test?retryWrites=true",
with no port, -_- , sorry about that

and, hashbrown-cms is best api based cms  i ever meet, open source and node server and js client, perfect

**Comment by mrzapp** [comment]
Ah, I see. No worries.

Thanks for the compliment, I appreciate it :smile:
