### ISSUE TITLE
ck editor without text color select, and with same errors, how about "react-draft-wysiwyg"

### ISSUE THREAD

**Issue by ghost** [Putaitu/putaitu-cms#284]
![image](https://user-images.githubusercontent.com/13210731/57191084-380fb400-6f54-11e9-9b5c-999de5077e27.png)

**Comment by mrzapp** [comment]
When does this error happen?

CKEditor is being completely replaced in v1.2 though, so when we've pushed that out, we shouldn't be seeing this nonsense anymore.

**Comment by mrzapp** [comment]
Your comment about text color select made me want to implement it in the new text editor, good idea

![color](https://i.imgur.com/lXZwQVQ.png)
