### ISSUE TITLE
Config permissions for the WYSIWYG editor

### ISSUE THREAD

**Issue by mrzapp** [Putaitu/putaitu-cms#285]
In order to streamline the authoring experience, we should implement switches for enabling/disabling WYSWYG editor features. The proposed features to toggle on/off are these:

*Paragraphs*
* h1
* h2
* h3
* h4
* h5
* h6

*Style*
* bold
* italic
* underline
* color

*Lists*
* Unordered list
* Ordered list

*Positioning*
* Indent
* Outdent
* Align left
* Center
* Justify
* Align right

*Media*
* Insert media

**Comment by mrzapp** [comment]
@silend if this sounds good to you, I'll move forward with implementation

**Comment by silend** [comment]
@mrzapp Sounds lovely. I would only also vote for `Insert media` to be optional, as I can think of cases where you want to _prevent_ content editors from inserting media files, if the frontend does not expect those.

**Comment by mrzapp** [comment]
sure, no problem

**Comment by mrzapp** [comment]
@silend this is now ready for testing. Remember to rebuild or watch the frontend with `npm run build:frontend` or `npm run watch:frontend`

![rte config](https://i.imgur.com/xHivMAL.png)
