### ISSUE TITLE
Improve the reliability of sorting content items

### ISSUE THREAD

**Issue by silend** [Putaitu/putaitu-cms#286]
There seems to be an issue with sorting content.

Say you have a "folder" with "sub items" in the content area, like this:

```
FOLDER
|— ITEM 1
|— ITEM 2
|— ITEM 3
|— ITEM 4
```

Now if you move `ITEM 4` after `ITEM 1`, the code in https://github.com/HashBrownCMS/hashbrown-cms/blob/51d0680ff5c4799649112f6a6fb6656a4e4ffb0c/src/Client/Views/Navigation/NavbarPane.js#L113 seems to look at `ITEM 1`, gets its index and increases it by 1.

If you now move `ITEM 3` after `ITEM 1` it does the same and `ITEM 3` and `ITEM 4` have the same value for `order`.

**Comment by silend** [comment]
BTW: In the UI this does not seem to be an issue 🤔 It is though when reading the JSON through the API as the content objects in the array are flatted (good!), but as multiple items have the same value the order can’t be restored by sorting.

**Comment by mrzapp** [comment]
I think the solution is to calculate all items in a "flat" manner instead.

Whenever an item is moved, it should only provide which node it is going to be above or below, and which parent, and then the backend updates all sort indices under the same parent

**Comment by mrzapp** [comment]
@silend this new logic has been implemented and is ready for testing. This change was long overdue.

**Comment by silend** [comment]
@mrzapp Sent you a backup from a real project in Matrix.

1. When one sorts items underneath _portfolio_ it seems to work now reliably on this child level. Although the parent level remains unchanged, which should not be the case if I understood you correctly, as all items are supposed to be sorted "flat".
2. Sorting the items on root level does not update all the items on this level -- it looks like the one before the _portfolio_ item (which has the sub items) breaks the sort loop somehow.

**Comment by mrzapp** [comment]
@silend Some particular circumstances in this project broke the solution, so I reworked it to make it more reliable. Changes pushed to v1.2

**Comment by silend** [comment]
@mrzapp It works reliably now on each individual level (eg. root elements, child elements of a root element). However, it does not do a "flat sort", but also maybe this is just a misunderstanding when we discussed this and never what you intended to do.

Let me try to explain … this is what the sort now does reliably:

```
ITEM [Sort: 1]
ITEM [Sort: 2]
|— ITEM [Sort: 1]
|— ITEM [Sort: 2]
|— ITEM [Sort: 3]
|— ITEM [Sort: 4]
ITEM [Sort: 3]
ITEM [Sort: 4]
```

This is what I _thought_ would happen:

```
ITEM [Sort: 1]
ITEM [Sort: 2]
|— ITEM [Sort: 3]
|— ITEM [Sort: 4]
|— ITEM [Sort: 5]
|— ITEM [Sort: 6]
ITEM [Sort: 7]
ITEM [Sort: 8]
```

Feel free to comment here, or we can also discuss in a chat.

**Comment by silend** [comment]
Clarified: It works as intended.
