### ISSUE TITLE
Babel compilation produces client-side errors

### ISSUE THREAD

**Issue by mrzapp** [Putaitu/putaitu-cms#287]

**Comment by mrzapp** [comment]
Decided to abandon Babel altogether and include a detection script that checks for vital features such as `async`, and redirect the user to an error page asking them to upgrade their browser, if one of the features are not supported.

To my knowledge, this only excludes IE11, and good riddance to that.

**Comment by mrzapp** [comment]
@silend the test here would be to visit localhost:8080 in an older browser, such as IE11

**Comment by silend** [comment]
@mrzapp This does not currently seem to work for me. When visited in IE11, I see the login page and can't get beyond it. Console shows that the browser wants to load
`GET /js/browser-check.js                       400 Bad Request`
which does not exist. Should this file be generated or what am I missing?

**Comment by mrzapp** [comment]
@silend my bad, I hadn't exluded it from the .gitignore, it should be there now

**Comment by silend** [comment]
@mrzapp `/js/browser-check.js` is now present and successfully loaded. Although the redirect is not working, I tested in:
+ Win 10, IE11
+ Win 8, IE10
+ Win8, Chrome 22

All these browsers are not supporting _async functions_, they all show the login page though, or at least try to do their best.

<img width="1392" alt="Bildschirmfoto 2019-06-10 um 15 22 31" src="https://user-images.githubusercontent.com/2743576/59199001-3fe6f780-8b95-11e9-812c-c4599f5a36f4.png">
<img width="1392" alt="Bildschirmfoto 2019-06-10 um 15 23 50" src="https://user-images.githubusercontent.com/2743576/59199011-42e1e800-8b95-11e9-8d48-f8f4379f8288.png">
<img width="1392" alt="Bildschirmfoto 2019-06-10 um 15 24 41" src="https://user-images.githubusercontent.com/2743576/59199020-45dcd880-8b95-11e9-84d9-44d5a9a2139f.png">

**Comment by mrzapp** [comment]
@silend I've reworked this solution, it seems to work on my Win10 VM with IE11 now

**Comment by silend** [comment]
@mrzapp Works brilliant! Bye bye IE11 :wave:

**Comment by mrzapp** [comment]
It will not be sorely missed
