### ISSUE TITLE
Error when trying to remove a connection

### ISSUE THREAD

**Issue by silend** [Putaitu/putaitu-cms#292]
On selecting `THIS CONNECTION > Remove` and error is displayed:
`TypeError: UI.confirmModal is not a constructor`

![2019-06-10-155259_1920x1056_scrot](https://user-images.githubusercontent.com/2743576/59207152-c6580500-8ba6-11e9-84bb-a2da9fb01898.png)

**Comment by mrzapp** [comment]
@silend Should be fixed now, remember to do `npm run build:frontend` before testing the latest changes.
