### ISSUE TITLE
Investigate memory leak

### ISSUE THREAD

**Issue by mrzapp** [Putaitu/putaitu-cms#293]
When large projects are loaded, there appears to be memory leaks in the DOM code

**Comment by mrzapp** [comment]
@silend There is no memory leak, it's as you mentioned that IndexedDB is just slow under certain circumstances (and totally unavailable in some others).

I am working on ditching the IndexedDB backend and just cache the schemas in memory (as they aren't such an ever expanding resource, like content and media is)

It should be ready soon. The way to test this would be to just perform a few regular tasks using the navigation panel.

**Comment by mrzapp** [comment]
@silend The schema memory cache seems to solve it

**Comment by silend** [comment]
@mrzapp Yes, looks all good now 👍
