### ISSUE TITLE
Remove deprecated entries from frontend QA test sheet

### ISSUE THREAD

**Issue by silend** [Putaitu/putaitu-cms#295]
The following features are going to be deprecated in `v1.2` and therefore should be removed from the QA test suite as well:

### Server

- [ ] Can restart instance

### Update

- [ ] Can perform update
- [ ] Update was pulled from stable branch

**Comment by mrzapp** [comment]
@silend if you don't mind, please remove them from here: https://github.com/HashBrownCMS/hashbrown-cms/blob/v1.2/src/Server/Views/ui-checklist.pug
