### ISSUE TITLE
Uploading media throws an error

### ISSUE THREAD

**Issue by silend** [Putaitu/putaitu-cms#296]
When uploading new media files, the request takes forever and probably times out at a certain point. The user then sees the following error:

![uploadingMedia](https://user-images.githubusercontent.com/2743576/60276802-95910300-98fc-11e9-8a69-12158844ff21.png)

**Comment by mrzapp** [comment]
@silend This should work now. Please test with a few different media types and pull the changes from the plugins repo

**Comment by mrzapp** [comment]
@silend since #297 you can forget the part I said about pulling the plugins repo :)

**Comment by silend** [comment]
Fixed :v:
