### ISSUE TITLE
Restructure plugins

### ISSUE THREAD

**Issue by mrzapp** [Putaitu/putaitu-cms#297]
@silend I have to admit that my idea of making the plugin folder a permanent Git submodule was a mistake. I've taken the steps to integrate the commonly used deployers and processors into the core instead, leaving only one processor (Jekyll) as a plugin.

To test this, you just need to check that your existing connections are working.

**Comment by mrzapp** [comment]
@silend BTW, this change unversions the /plugins folder, so it'd be a good idea to remove the contents of it, at least the "api", "json", "uischema.org", "git" and "filesystem" folders.

**Comment by silend** [comment]
@mrzapp I receive an error when trying to upload media both for my existing test environment (also cleaned out the `/plugins` folder as suggested) and when I pull a fresh clone and run it via docker on my local machine.

<img width="633" alt="Bildschirmfoto 2019-07-30 um 11 58 32" src="https://user-images.githubusercontent.com/2743576/62120295-9b924f00-b2c1-11e9-952d-8503083cea05.png">

**Comment by silend** [comment]
Console log:

<img width="470" alt="Bildschirmfoto 2019-07-30 um 12 00 57" src="https://user-images.githubusercontent.com/2743576/62120355-b82e8700-b2c1-11e9-98c3-089866ec10d9.png">

**Comment by silend** [comment]
Server log:
```
2019.07.30 09:58:19 | FileSystemDeployer | Writing file "/Users/silend/dev/code/hashbrown-cms/data/media/954c88b7cb2f35bf/Bildschirmfoto 2019-07-26 um 21.55.55.png"...
2019.07.30 09:58:19 | MediaController | Error: ENOENT: no such file or directory, open '/Users/silend/dev/code/hashbrown-cms/data/media/954c88b7cb2f35bf/Bildschirmfoto 2019-07-26 um 21.55.55.png'
2019.07.30 10:02:21 | FileSystemDeployer | Writing file "/Users/silend/dev/code/hashbrown-cms/data/media/e06e0cdb1d59ff42/test.png"...
2019.07.30 10:02:21 | MediaController | Error: ENOENT: no such file or directory, open '/Users/silend/dev/code/hashbrown-cms/data/media/e06e0cdb1d59ff42/test.png'
```

**Comment by silend** [comment]
Possibly related to #296

**Comment by mrzapp** [comment]
@silend I was able to reproduce the problem, it was a race condition between 2 asynchronous functions where I had forgotten to await the first one. Should be fixed now.

**Comment by silend** [comment]
@mrzapp Yes, works like a charm now.
