### ISSUE TITLE
Media and content labels in collapsed mode

### ISSUE THREAD

**Issue by mrzapp** [Putaitu/putaitu-cms#298]
Currently, collapsed media references look like this:

![image](https://user-images.githubusercontent.com/2747428/61272138-b08dbf00-a7a6-11e9-8a80-da53bfeb4737.png)

We need a solid way to detect if a string is a reference to a resource and fetch a proper label based on that reference. Perhaps a metadata cache is in order?

**Comment by mrzapp** [comment]
Solved by offloading the responsibility to the FieldEditor view

@silend this can be tested by looking through content with lots of collapsed fields, like arrays and structs, and check if they all have sensible names

**Comment by silend** [comment]
@mrzapp Nicely solved 👍
