### ISSUE TITLE
Users can work on the same project in parallel and overwrite each other's changes

### ISSUE THREAD

**Issue by nkear003** [Putaitu/putaitu-cms#303]
It would be great if we could find a way to prevent users from being able to overwrite each other's changes.

**Comment by mrzapp** [comment]
@nkear003 Absolutely. Where are you most commonly experiencing this? When editing content or anything else?

**Comment by nkear003** [comment]
@mrzapp Hey Jeppe. I have never experienced this issue on my own. I made the issue on behalf of AFKM. I will ask the team. I think editing content would be the main issue, since that's where we have most people working at the same time, although I assume it could also happen when editing schemas. I'll write back if I get some more info.

**Comment by mrzapp** [comment]
@silend @nkear003 I've committed a solution to this issue on the `develop` branch. Please try it out and let me know if the experience is good enough. I'll let you in on the implementation details later if you like.

The implementation should be working for all resource types (content, schemas, forms, connections), so it'd be great if you could test them all.

**Comment by nkear003** [comment]
@mrzapp Thanks Jeppe, I will test it out this week.

**Comment by nkear003** [comment]
@mrzapp I didn't get to this when I said I would, sorry about that. Will test soon, thank you :)

**Comment by mrzapp** [comment]
@nkear003 No worries, take your time :)

**Comment by silend** [comment]
@mrzapp Seems to work reliably, but still need to test more thoroughly.
