### ISSUE TITLE
ArrayEditor improvements

### ISSUE THREAD

**Issue by mrzapp** [Putaitu/putaitu-cms#304]
* Add typeahead search to the schema picker
* Fix new items not rendering inherited fields
* Improve readability of "add item" buttons

**Comment by mrzapp** [comment]
@milesleif @nkear003 this should work now with the latest code on the `develop` branch. Also fixed an issue with inherited fields not being populated when adding new items to an array

**Comment by silend** [comment]
@mrzapp Seems to work reliably, but still need to test more thoroughly.
