### ISSUE TITLE
after first setup css error

### ISSUE THREAD

**Issue by mustafa-colakoglu** [Putaitu/putaitu-cms#305]
Hi.

I finished first setup and i logined as admin.

But i guess css files dont existing. How can i find css files or css directory?

Good works.

Screenshot : 
![image](https://user-images.githubusercontent.com/9257902/64701628-cae7ce80-d4b1-11e9-8222-da50e6d14cef.png)

**Comment by mrzapp** [comment]
Did you follow the steps [here](https://github.com/HashBrownCMS/hashbrown-cms#running-hashbrown)? Looks like the frontend files haven't been built
