### ISSUE TITLE
New UI

### ISSUE THREAD

**Issue by mrzapp** [Putaitu/putaitu-cms#307]
The entire UI has been rewritten to address long standing usability issues unsolvable using the previous structure.

Highlights:
- Views:
  - Divided into entities and templates
  - Using state objects, making them much more flexible
  - Using function scopes, making their design more restricted and lean
- CSS rewritten to make theming possible
- Fields manage their own data, making the content editor faster to render
- New schema editor
- Drag and drop sorting and nesting for resources in the left side panel :tada: 
- Better UI for creating media folders

**Comment by mrzapp** [comment]
@silend A regular UI test would be all that's needed for this one. Check out the the "lightblue" theme from the user menu (top right corner) and let me know what you think :) We can add more themes anytime, it's just a couple of CSS variables.

**Comment by silend** [comment]
@mrzapp Looks super neat ✌️ I have to test it thoroughly, but my impression so far is that it is a huge UX improvement.
