### ISSUE TITLE
When uploading backup, title is blank. Also, non-timestamps don't work.

### ISSUE THREAD

**Issue by mrzapp** [Putaitu/putaitu-cms#314]

**Comment by silend** [comment]
Uploading of backups seems to work fine now, thus closing this issue.

But I am not really sure, what `Also, non-timestamps don't work.`  means, so please feel free to re-open the issue @mrzapp

**Comment by mrzapp** [comment]
@silend It just means that any backup with a file name not matching a UNIX time stamp format would not work.

**Comment by silend** [comment]
Ah, makes sense. Confirmed to work for non-UNIX time stamp file names.
