### ISSUE TITLE
Route `/test` does not seem to work with new theming

### ISSUE THREAD

**Issue by silend** [Putaitu/putaitu-cms#315]
@mrzapp  The UI is broken, yet there are no errors in the console or the network inspector, which makes me suspect that this has to do with the new theming capabilities of v1.3.

<img width="965" alt="Bildschirmfoto 2019-10-24 um 10 51 40" src="https://user-images.githubusercontent.com/2743576/67469628-c71c9f80-f64c-11e9-8a33-ba455667306c.png">

**Comment by mrzapp** [comment]
@silend should be fixed now

**Comment by silend** [comment]
This works now, I can confirm.

Only the checkboxes are simple checkboxes now, instead of toggle switches as they have been before. But as this is just eye candy, I'd label it as nice to have.

Feel free to close the issue @mrzapp
