### ISSUE TITLE
Link in update prompt is displayed in plain

### ISSUE THREAD

**Issue by silend** [Putaitu/putaitu-cms#316]
In v1.3 the HTML in the update dialogue is displayed in plain text:
<img width="420" alt="Bildschirmfoto 2019-10-28 um 15 32 41" src="https://user-images.githubusercontent.com/2743576/67687586-d1b29e00-f998-11e9-9950-083fd3c87b3b.png">

**Comment by mrzapp** [comment]
Should work now

**Comment by silend** [comment]
Confirmed.

<img width="426" alt="Bildschirmfoto 2019-10-28 um 15 57 27" src="https://user-images.githubusercontent.com/2743576/67689723-083de800-f99c-11e9-8921-619e973a70be.png">
