### ISSUE TITLE
Mention upsert option in API docs for creating schemas

### ISSUE THREAD

**Issue by silend** [Putaitu/putaitu-cms#320]
The API docs describe the endpoint for setting a schema via a POST request.

The optional query parameter flag `&create=true` to decide if the document should be _created_ or _updated_ should be mentioned in the API docs otherwise the creation silently fails if the document does not exist, yet.

See also: https://github.com/HashBrownCMS/hashbrown-cms/blob/stable/src/Server/Controllers/SchemaController.js#L105

**Comment by mrzapp** [comment]
It should probably also not fail silently, to be perfectly honest

**Comment by mrzapp** [comment]
@silend ready for testing now. The API docs are parsed from the stable branch code, so it will update when the develop branch is merged.
