### ISSUE TITLE
Route /js/plugins.js is not working

### ISSUE THREAD

**Issue by silend** [Putaitu/putaitu-cms#331]
When navigating into a project, network console shows the attempt to load `/js/plugins.js`, but the request has HTTP status `502`.

![grafik](https://user-images.githubusercontent.com/2743576/72628883-8d0f2100-394f-11ea-9ca6-e21d4a7dbae3.png)

**Comment by mrzapp** [comment]
It will happen when no plugins are installed. We need the webpack script to create a dummy file if that's the case.

**Comment by mrzapp** [comment]
@silend can you checkout the latest `develop` code and run `npm run build:frontend` again? Should work now

**Comment by silend** [comment]
@mrzapp Yes, it does work now.
