### ISSUE TITLE
Images with extension .jpeg are not recognized as images

### ISSUE THREAD

**Issue by silend** [Putaitu/putaitu-cms#332]
To reproduce (tested against v1.3.6):

+ Upload an image in _Media_ with the extension `.jpeg`
+ The image does not show, instead a generic file icon is being displayed
![Screenshot from 2020-01-24 15-16-09](https://user-images.githubusercontent.com/2743576/73075686-c2ba8980-3ebc-11ea-8a00-c321afda75db.png)
+ Change the extension by renaming the file (using `.jpg`)
+ Reload
+ The image is displayed correctly 
![Screenshot from 2020-01-24 15-16-41](https://user-images.githubusercontent.com/2743576/73075813-0c0ad900-3ebd-11ea-8c05-2d07042c16c6.png)

**Comment by mrzapp** [comment]
The fix for this issue is to add 'jpeg' to this case statement: https://github.com/HashBrownCMS/hashbrown-cms/blob/develop/src/Common/Entity/Resource/Media.js#L65

**Comment by silend** [comment]
@mrzapp Jup, that works. Thanks for the hint.
