### ISSUE TITLE
richText should save with language keys in multilanguage context

### ISSUE THREAD

**Issue by milesleif** [Putaitu/putaitu-cms#335]
Hashbrown Version **v1.3.6**

Content from richText schemas, that are part of an array which itself has a "multilanguage" flag are now saved differently than in version 1.1. In the current version, the richTexts nor the array is saved with any information about the language. 

Having this schema set up:

```
{
  "config": {
    "struct": {
      "texts": {
        "label": "Texts",
        "schemaId": "array",
        "config": {
          "minItems": "1",
          "maxItems": "2",
          "allowedSchemas": [
            "richText"
          ]
        },
        "multilingual": true
      }
    }
  }
}
```

This screencap shows that is appearantly not possible to save the text in the "Texts"-Array:

![Kapture 2020-03-17 at 21 55 45](https://user-images.githubusercontent.com/1314903/76901945-6ad84780-689b-11ea-9a24-4d7601f36c36.gif)

But we can see in the pure json data, that the texts items are actually saved, but differently than before.

JSON in ver 1.3.6 after save:

```
{
    "texts": [
        {
            "value": "<p>This is my text</p>\n",
            "schemaId": "richText"
        }
    ]
}
```

Expected representation on the other hand is this:

JSON Data in ver1.1

```
{
    "texts": {
        "de": [
            {
                "value": "<p>This is my text</p>\n",
                "schemaId": "richText"
            }
        ]
    }
}
```

as we can see, the newer version lacks the language keys when saving  a richText that sits inside an array (which has set the flag for multilang).

The UI of Hashbrown seems to agree with me, since it also does not seem to find the expected structure and thus shows an "empty" state after a reload.

Unfortunately this breaks the saving process fundamentally and we kinda need a solution here urgently.

**Comment by milesleif** [comment]
@mrzapp could you possibly have a look at that?

**Comment by mrzapp** [comment]
@milesleif oh dang, is this something that only happens with rich text editors? Seems to me like an array issue

**Comment by milesleif** [comment]
@mrzapp yes, this is only richText editors in the context of arrays.

**Comment by milesleif** [comment]
@mrzapp but let me check if it also occurs when I use something different in the arrays.

**Comment by mrzapp** [comment]
It was in the ArrayEditor, I'm pushing the fix now

**Comment by milesleif** [comment]
@mrzapp does not seem to be a problem with richText but more, as you stated, with the array when having the "multilingual" flag. Using for example strings in this context creates the same result (strings are saved but without language key):

```
{
    "texts": [{
        "schemaId": "string",
        "value": "Hello there"
    }]
}

```

expected output is

```
{
    "texts": {
        "de": [{
            "schemaId": "string",
            "value": "Hello there"
        }]
    }
}
```

**Comment by milesleif** [comment]
@mrzapp woah, you are too fast for me :)

**Comment by mrzapp** [comment]
*Jeppe blows the smoke off the barrel of his smoking revolver, and in a raspy voice he speaks from beneath his white fedora:*

> The COVID-19 isolation halted almost all of my paid projects, so I have had nothing to do lately. Stay cool, kids :sunglasses:

**Comment by silend** [comment]
:sweat_smile:

**Comment by milesleif** [comment]
@mrzapp hilarious! And the fix works, too: =D
