### ISSUE TITLE
EXIF image orientation

### ISSUE THREAD

**Issue by silend** [Putaitu/putaitu-cms#336]
If uploaded images have `exif::orientation` set, this information is currently being ignored. This results in images being displayed with wrong orientation.

Several DSLR cameras models save images using that EXIF data, some image viewers seem to do the same to rotate images in a lossless manner.

ImageMagick provides commands to fix this, eg. with `convert`
`convert your-image.jpg -auto-orient output.jpg`
or `mogrify`
`mogrify -auto-orient your-image.jpg`

As HashBrown uses ImageMagick, I was wondering if there's the possibility to teach HashBrown how to handle such cases correctly.

**Comment by mrzapp** [comment]
@silend if it's the preview generated by the media cache, we just need to add the `-auto-orient` flag to the command.

I've implemented a fix in `v1.4`, can you test it?

**Comment by silend** [comment]
@mrzapp Gladly. Unfortunately I seem unable to get `v1.4` running on my end :sweat_smile: 

The logs for the node container throwing errors:
```
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'body-parser'
Require stack:
- /opt/hashbrown-cms/src/Server/Controller/FormController.js
- /opt/hashbrown-cms/src/Server/Controller/index.js
- /opt/hashbrown-cms/src/Server/index.js
- /opt/hashbrown-cms/hashbrown.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/opt/hashbrown-cms/src/Server/Controller/FormController.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/hashbrown-cms/src/Server/Controller/FormController.js',
    '/opt/hashbrown-cms/src/Server/Controller/index.js',
    '/opt/hashbrown-cms/src/Server/index.js',
    '/opt/hashbrown-cms/hashbrown.js'
  ]
}
```

Do I also need to do something with the new `npm run db:docker` command?

**Comment by mrzapp** [comment]
Huh, my version of Node.js is a bit more lenient, apparently. I've removed that reference now, so you can pull again.

The new `db:docker` command is just a convenient way to enter the MongoDB container, nothing fancy :grin:

**Comment by silend** [comment]
Thanks that helped. A bit :sweat_smile: 
But I'm still having issues here, as some `/api` routes are non existent which the UI tries to use. 

I tried it also with a complete fresh installation. Creating the admin account works, but not much else, even adding a new project fails:

![Screenshot from 2020-03-20 18-12-52](https://user-images.githubusercontent.com/2743576/77188555-795e7300-6ad6-11ea-9846-86d0828a7bfb.png)


![Screenshot from 2020-03-20 17-57-35](https://user-images.githubusercontent.com/2743576/77187890-72833080-6ad5-11ea-8200-f82361ffc732.png)

With a populated DB (from v1.3.7) I can use branch `v1.4` to browse projects, but media files are not being previewed, because of the "missing" API. Weirdly enough I can succesfully upload files.

Any ideas where I am being stupid?

PS. `db:docker` is a neat shortcut.

**Comment by mrzapp** [comment]
And you built the frontend too? If you did, which node.js version are you running?

**Comment by silend** [comment]
Running the following makes the error reproducable for me:

```
git clone https://github.com/HashBrownCMS/hashbrown-cms.git --recursive
cd ./hashbrown-cms
git checkout v1.4
npm i
npm run update
npm run start:docker
```

This should built everything just fine, no?

I am running the recent LTS version `v12.16.1`

**Comment by mrzapp** [comment]
Fixes for the project controller has been pushed to v1.4, should work now. It's all part of the migration away from express.js :sweat_smile:

**Comment by silend** [comment]
With the most recent changes I am unable to create an admin user on a fresh install.

When I submit the form for the new admin user, the following error is printed to the browser window:
![Screenshot from 2020-03-24 11-03-41](https://user-images.githubusercontent.com/2743576/77413399-91c4db00-6dbf-11ea-841f-3da9cb66c18e.png)

But nevermind. I maybe should just await the migration away from express.js :sweat_smile:

**Comment by mrzapp** [comment]
> But nevermind. I maybe should just await the migration away from express.js

No, this is great :D You're testing a bunch of things I didn't expect you to at the moment, but it's getting things done. I've committed a fix for the setup flow now.

**Comment by mrzapp** [comment]
@silend the fix we talked about has been committed now
