### ISSUE TITLE
richText editor should be able to hide WYSIWYG view completely

### ISSUE THREAD

**Issue by milesleif** [Putaitu/putaitu-cms#344]
With children of the richText schema it is possible to toggle Markdown- and HTML-View on and off, as well as controlling the displayed buttons for the WYSIWYG-Editor, which is pretty cool. 

Alas the issue that clients can copy/paste text with malicious invisible markup remains as long as WYSIWYG is used. Thank you MS Word. -.-

At the moment there is no way to not use the WYSIWYG-Editor at all.

It would be really helpful if that one could be un-displayed as well so that only markdown or html-editor remains.

Bonus-Feature would be a markdown editor which still provides some helper buttons for formatting (if you for example know the textarea of the Panel of Kirby CMS, you know what I mean).

@mrzapp is there any way to achieve that? Or prevent pasting bullshit that messes with the markup in another way?

**Comment by mrzapp** [comment]
@milesleif disabling it would be a pretty easy change.

We can add the control here in the config template: https://github.com/HashBrownCMS/hashbrown-cms/blob/stable/template/field/config/richTextEditor.js#L4

And then do the check for the setting here in the field template: https://github.com/HashBrownCMS/hashbrown-cms/blob/stable/template/field/editor/richTextEditor.js#L8

You can try it out, just change those 2 files and `npm run build:frontend`

If it's to your liking, we can push it in a patch :)

About a HTML sanitiser, we can definitely do that, however we should decide on which rules to go by first. Like, do we remove certain elements, or do we change them into other ones?

About adding buttons to the markdown editor, we can make a separate issue for that. I agree, that would be handy.

**Comment by milesleif** [comment]
Thx @mrzapp , will try that and also open a separate issue for the improved markdown editor

**Comment by milesleif** [comment]
@mrzapp quick question: how do you want me to commit / push it? Doing a commit in `develop`-branch? From there going further to `stable` after a review? Or somewhat completely different? ^^

**Comment by mrzapp** [comment]
@milesleif yeah, just commit the fix to `develop`, and we'll test it before the next release :)

**Comment by milesleif** [comment]
@mrzapp after some hiccups with the installation (which was basically me not understanding caching -.-), I implemented this in branch `develop` with the commit above. 

Feel free to have a look and if I didn't fuck anything up codewise, be my guest and close this issue.

**Comment by mrzapp** [comment]
@milesleif no, you were right to be confused, the "updatedOn" date was not being propagated sensibly through the schema inheritance, so the cache wasn't being invalidated properly. It's fixed now, and your implementation looks good to me :)
