### ISSUE TITLE
Search for media in library should be accessible with keystrokes "enter" and "escape"

### ISSUE THREAD

**Issue by milesleif** [Putaitu/putaitu-cms#347]
Occurs in Hashbrown Version 1.3 and 1.4

Both the search field inside the media library and the "pick media" in the media selection dialog provide a handy search field. After entering the search phrase the search only starts when one _clicks_ on the search icon (magnifier).

In general, expected behavior for text inputs is also to react to keystrokes like enter. The lack of that responsiveness in this case confuses some people to that extend that they think, the search is not functional (those people being me for some time now, tbh). 

Suggestion: make the search input field react to keystrokes "enter" to confirm the query and "escape" to empty the form and query - just like those two buttons at the side do. 

![Bildschirmfoto 2020-11-09 um 17 36 58](https://user-images.githubusercontent.com/1314903/98569645-d6e83f80-22b2-11eb-8a78-428acdb23d34.jpg)

![Bildschirmfoto 2020-11-09 um 17 36 30](https://user-images.githubusercontent.com/1314903/98569652-d8b20300-22b2-11eb-8d26-e1c7fddc45b6.jpg)

**Comment by mrzapp** [comment]
@milesleif this fix should be in the `develop` branch now. Are you guys using the `1.4` version, BTW? I have not had any time to test everything out myself, and it has been a bit quiet with contributor testing lately

**Comment by milesleif** [comment]
@mrzapp thank you very much.

Unfortunately we do not use `1.4` in production yet (hence a hotfix for v1.3, see recent pull request) – at the moment we lack resources for testing ourselves, but we are working on it.
