### ISSUE TITLE
the latest code in branch master can not be run

### ISSUE THREAD

**Issue by gakaki** [Putaitu/putaitu-cms#349]
but the tag1.38 is running with no errors

http://localhost:8080/

the error is (in the master branch latest)

Error
The "path" argument must be of type string. Received undefined
Go to dashboard

**Comment by mrzapp** [comment]
@gakaki I'm unable to reproduce this error, but I remember it popping up a while ago. Did you use `npm run update` or how did you get the latest code? Also, did you restart the app afterwards?

If you're still seeing the error, then I will need the output from the console. If you're running HashBrown in a docker-compose setup, you can use `npm run watch:docker` to see the log messages.

**Comment by gakaki** [comment]
1.38 is ok no problem   

just clone the 1.40tag
 than start a clearn mongodb instance no any othger hb_ prefix database , a clean mongodb instance from scratch.
npm. run start
http://localhost:8080/      

the error. is 

Error
The "path" argument must be of type string. Received undefined
Go to dashboard

**Comment by mrzapp** [comment]
@gakaki thanks for the bug report, good find! It's patched now in 1.4.1

This bug only affected fresh installations.
