### ISSUE TITLE
"Page" not populating in "Create new content" menu

### ISSUE THREAD

**Issue by ki9us** [Putaitu/putaitu-cms#351]
How do I add a new `Page`? It doesn't appear in the schema dropdown when I try to create a new content.  

![image](https://user-images.githubusercontent.com/10123447/147414153-bba00f95-3df2-463a-bc12-3bf751507717.png)

If I create a new custom schema, that does appear in the list.  

![image](https://user-images.githubusercontent.com/10123447/147414133-7cc76aff-bda3-4844-aefa-e977de02fc2c.png)

**Comment by mrzapp** [comment]
That's intended, you create your own schemas based on the `Page` :)
